package edu.udel.cis.vsl.civl.err;

/**
 * Thrown when a path condition becomes unsatisfiable, typically due to a side
 * effect from evaluating an expression.
 * 
 * @author siegel
 * 
 */
public class UnsatisfiablePathConditionException extends Exception {

	/**
	 * Generated by Eclipse.
	 */
	private static final long serialVersionUID = -8712277042005191993L;

}
