package edu.udel.cis.vsl.civl.model.common;

import edu.udel.cis.vsl.civl.model.IF.CIVLException;
import edu.udel.cis.vsl.civl.model.IF.CIVLSource;

public class ModelFactoryException extends CIVLException {

	/**
	 * generated by eclipse
	 */
	private static final long serialVersionUID = 1L;

	public ModelFactoryException(String message, CIVLSource source) {
		super(message, source);
	}

}
